environment = Environment(CC = "x86_64-elf-gcc",
						  CXX = "x86_64-elf-g++",
						  CXXFLAGS = "-fpic -ffreestanding -std=gnu++11 -O2 -Wall -mcmodel=large -mno-red-zone -mno-mmx -mno-sse -mno-sse2 -c",
						  OBJCOPY = "x86_64-elf-objcopy")

source_files = []
include_dirs = []

source_files += Glob("*.cpp")
source_files += Glob("thoth/*.cpp")

include_dirs += ["../include/libc"]

kernel_objects = environment.Object(source_files, CPPPATH = include_dirs)
