environment = Environment(CC = "i686-elf-gcc",
						  CXX = "i686-elf-g++",
						  CXXFLAGS = "-fpic -ffreestanding -std=gnu++11 -O2 -Wall",
						  LINKER = "i686-elf-g++",
						  LINKFLAGS = "-T linker.ld -ffreestanding -O2 -nostdlib -lgcc",
						  OBJCOPY = "i686-elf-objcopy")

source_files = []

source_files += Glob("*.cpp")
source_files += Glob("thoth/*.cpp")

for i in source_files:
	print(i)

kernel_objects = environment.Object(source_files)
