environment = Environment(CC = "x86_64-elf-gcc",
						  CXX = "x86_64-elf-g++",
						  AS = "x86_64-elf-g++",
						  ASFLAGS = "-fpic -ffreestanding -Wall -Wextra -mcmodel=large -mno-red-zone -mno-mmx -mno-sse -mno-sse2 -c",
						  CXXFLAGS = "-fpic -ffreestanding -Wall -Wextra -mcmodel=large -mno-red-zone -mno-mmx -mno-sse -mno-sse2 -c",
						  OBJCOPY = "x86_64-elf-objcopy")

source_files = []
include_dirs = []

source_files += Glob('*.s')

include_dirs += ["."]

environment.Object(source_files)
