import os

environment = Environment(CC = "x86_64-elf-g++",
						  CXX = "x86_64-elf-g++",
						  CXXFLAGS = "-DKERNEL_SPACE -fpic -ffreestanding -std=gnu++11 -O2 -Wall -mcmodel=large -mno-red-zone -mno-mmx -mno-sse -mno-sse2 -c",
						  CFLAGS = "-DKERNEL_SPACE -fpic -ffreestanding -std=gnu++11 -O2 -Wall -mcmodel=large -mno-red-zone -mno-mmx -mno-sse -mno-sse2 -c",
						  OBJCOPY = "x86_64-elf-objcopy")

source_files = []
include_dirs = []

source_files += Glob("*.c")

include_dirs += ["../../include/libc"]

environment.Object(source_files, CPPPATH = include_dirs)
