project_name = "Thoth"
os_bin_name = project_name.lower() + ".bin"

subdirs = []

#Bootstrap
subdirs += ["bootstrap/SConscript"] #Bootstrap subdirectory
subdirs += ["kernel/SConscript"] #Kernel subdirectory
subdirs += ["library/SConscript"] #Libraries subdirectory
subdirs += ["program/SConscript"] #Programs subdirectory

SConscript(subdirs) #Perform subdirectory tasks

environment = Environment(CC = "i686-elf-gcc",
						  CXX = "i686-elf-g++",
						  LINKER = "i686-elf-g++",
						  LINKFLAGS = "-T src/linker.ld -ffreestanding -O2 -nostdlib -lgcc")

kernel_objects = []

#Bootstrap objects
kernel_objects += Glob("bootstrap/*.o")

#Kernel objects
kernel_objects += Glob('kernel/*.o')
kernel_objects += Glob('kernel/c/*.o')
kernel_objects += Glob('kernel/terminal/*.o')

#Library objects
kernel_objects += Glob('library/libstd/*.o')


#Link everything into the main kernel binary
kernel_bin = environment.Program(os_bin_name, kernel_objects)

Depends(kernel_bin, "linker.ld")