project_name = "Thoth"
os_bin_name = project_name.lower() + ".bin"

subdirs = []

subdirs += ["lib/SConscript"] #Libraries subdirectory
subdirs += ["boot/SConscript"] #Bootstrap subdirectory
subdirs += ["kernel/SConscript"] #Kernel subdirectory
subdirs += ["app/SConscript"] #Programs subdirectory

SConscript(subdirs) #Perform subdirectory tasks

environment = Environment(CC = "x86_64-elf-gcc",
						  CXX = "x86_64-elf-g++",
						  LINKER = "x86_64-elf-g++",
						  LINKFLAGS = "-T src/linker.ld -fpic -ffreestanding -O2 -nostdlib -lgcc -mcmodel=large -mno-red-zone -mno-mmx -mno-sse -mno-sse2 -z max-page-size=4096")

kernel_objects = []

#Kernel standard library objects
kernel_objects += Glob('lib/libk/*.o')

#Bootstrap objects
kernel_objects += Glob("boot/*.o")

#Kernel objects
kernel_objects += Glob('kernel/*.o')
kernel_objects += Glob('kernel/thoth/*.o')


#Link everything into the main kernel binary
kernel_bin = environment.Program(os_bin_name, kernel_objects)

Depends(kernel_bin, "linker.ld")
