environment = Environment(CC = "i686-elf-gcc",
						  CXX = "i686-elf-g++",
						  CXXFLAGS = "-fpic -ffreestanding -std=gnu++11 -O2 -Wall -Wextra",
						  LINKER = "i686-elf-g++",
						  LINKFLAGS = "-ffreestanding -O2 -nostdlib -lgcc",
						  OBJCOPY = "i686-elf-objcopy")

source_files = []

source_files += Glob('*.cpp')
source_files += Glob('libc/*.cpp')

objects = environment.Object(source_files)
